<a href="https://colab.research.google.com/github/Siva1212-genious/ML-Algorithms---ScikitLearn/blob/main/Decision_Tree_Classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install legacy-cgi --quiet

In [2]:
!pip install opendatasets --quiet

In [3]:

import opendatasets as od

dataset_url = 'https://www.kaggle.com/jsphyg/weather-dataset-rattle-package'

od.download(dataset_url)

Please provide your Kaggle credentials to download this dataset. Learn more: http://bit.ly/kaggle-creds
Your Kaggle username: siva
Your Kaggle Key: ··········
Dataset URL: https://www.kaggle.com/datasets/jsphyg/weather-dataset-rattle-package
Downloading weather-dataset-rattle-package.zip to ./weather-dataset-rattle-package

100%|██████████| 3.83M/3.83M [00:01<00:00, 3.77MB/s]

In [4]:
import os

data_dir = './weather-dataset-rattle-package'

os.listdir(data_dir)

['weatherAUS.csv']

In [5]:
dataset = data_dir + '/weatherAUS.csv'

In [6]:
import pandas as pd

raw_data = pd.read_csv(dataset)

raw_data

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,...,71.0,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,No,No
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,...,44.0,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,No,No
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,38.0,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No,No
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,...,45.0,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,No,No
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,ENE,...,82.0,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145455,2017-06-21,Uluru,2.8,23.4,0.0,NaN,NaN,E,31.0,SE,...,51.0,24.0,1024.6,1020.3,NaN,NaN,10.1,22.4,No,No
145456,2017-06-22,Uluru,3.6,25.3,0.0,NaN,NaN,NNW,22.0,SE,...,56.0,21.0,1023.5,1019.1,NaN,NaN,10.9,24.5,No,No
145457,2017-06-23,Uluru,5.4,26.9,0.0,NaN,NaN,N,37.0,SE,...,53.0,24.0,1021.0,1016.8,NaN,NaN,12.5,26.1,No,No
145458,2017-06-24,Uluru,7.8,27.0,0.0,NaN,NaN,SE,28.0,SSE,...,51.0,24.0,1019.4,1016.5,3.0,2.0,15.1,26.0,No,No
145459,2017-06-25,Uluru,14.9,NaN,0.0,NaN,NaN,NaN,NaN,ESE,...,62.0,36.0,1020.2,1017.9,8.0,8.0,15.0,20.9,No,NaN

In [7]:
# Now, we will clean the data by seperating the numerical_columns and categorical_columns,
# Numerical_Columns will be cleaned by imputing technique and then we can either scale or we can just leave them like that.
# Categorical_Columns can be cleared by filling the empty columns with 'unknown' and we can encode them.

In [8]:
import numpy as np

numeric_colm = raw_data.select_dtypes(include = np.number).columns.tolist()
categorical_colm = raw_data.select_dtypes(include = 'object').columns.tolist()

In [9]:
numeric_colm, categorical_colm

(['MinTemp',
  'MaxTemp',
  'Rainfall',
  'Evaporation',
  'Sunshine',
  'WindGustSpeed',
  'WindSpeed9am',
  'WindSpeed3pm',
  'Humidity9am',
  'Humidity3pm',
  'Pressure9am',
  'Pressure3pm',
  'Cloud9am',
  'Cloud3pm',
  'Temp9am',
  'Temp3pm'],
 ['Date',
  'Location',
  'WindGustDir',
  'WindDir9am',
  'WindDir3pm',
  'RainToday',
  'RainTomorrow'])

In [10]:
# Let's clean the numeric columns first

In [11]:
raw_data[numeric_colm].isna().sum()

MinTemp           1485
MaxTemp           1261
Rainfall          3261
Evaporation      62790
Sunshine         69835
WindGustSpeed    10263
WindSpeed9am      1767
WindSpeed3pm      3062
Humidity9am       2654
Humidity3pm       4507
Pressure9am      15065
Pressure3pm      15028
Cloud9am         55888
Cloud3pm         59358
Temp9am           1767
Temp3pm           3609
dtype: int64

In [12]:
# Now we will use imputer function to clean the empty columns in by using mean strategy

In [13]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy = 'mean')

raw_data[numeric_colm] = imputer.fit(raw_data[numeric_colm]).transform(raw_data[numeric_colm])

In [14]:
raw_data[numeric_colm].isna().sum()

MinTemp          0
MaxTemp          0
Rainfall         0
Evaporation      0
Sunshine         0
WindGustSpeed    0
WindSpeed9am     0
WindSpeed3pm     0
Humidity9am      0
Humidity3pm      0
Pressure9am      0
Pressure3pm      0
Cloud9am         0
Cloud3pm         0
Temp9am          0
Temp3pm          0
dtype: int64

In [15]:
# Our numeric columns are good with no empty columns.

# Now we can focus on the categorical columns and replace empty columns with 'unknown'

In [16]:
raw_data[categorical_colm] = raw_data[categorical_colm].fillna('unknown')

In [17]:
raw_data[categorical_colm].isna().sum()

Date            0
Location        0
WindGustDir     0
WindDir9am      0
WindDir3pm      0
RainToday       0
RainTomorrow    0
dtype: int64

In [18]:
# now we need to drop all the columns which have unknown in 'RainToday', 'RainTomorrow'. Because,

In [19]:
#filtered_data = raw_data[raw_data['RainToday'] & raw_data['RainTomorrow'] != 'unknown']   #Not Working

filtered_data = raw_data[(raw_data['RainToday'] != 'unknown') & (raw_data['RainTomorrow'] != 'unknown')]

In [20]:
filtered_data[filtered_data['RainToday'] == 'unknown']

Empty DataFrame
Columns: [Date, Location, MinTemp, MaxTemp, Rainfall, Evaporation, Sunshine, WindGustDir, WindGustSpeed, WindDir9am, WindDir3pm, WindSpeed9am, WindSpeed3pm, Humidity9am, Humidity3pm, Pressure9am, Pressure3pm, Cloud9am, Cloud3pm, Temp9am, Temp3pm, RainToday, RainTomorrow]
Index: []

[0 rows x 23 columns]

In [21]:
filtered_data[filtered_data['RainTomorrow'] == 'unknown']

Empty DataFrame
Columns: [Date, Location, MinTemp, MaxTemp, Rainfall, Evaporation, Sunshine, WindGustDir, WindGustSpeed, WindDir9am, WindDir3pm, WindSpeed9am, WindSpeed3pm, Humidity9am, Humidity3pm, Pressure9am, Pressure3pm, Cloud9am, Cloud3pm, Temp9am, Temp3pm, RainToday, RainTomorrow]
Index: []

[0 rows x 23 columns]

In [22]:
# Now we can remove the 'Date', 'RainTomorrow' columns

In [23]:
input_columns = list(filtered_data)[1:-1]
target_columns = 'RainTomorrow'

In [24]:
input_columns, target_columns

(['Location',
  'MinTemp',
  'MaxTemp',
  'Rainfall',
  'Evaporation',
  'Sunshine',
  'WindGustDir',
  'WindGustSpeed',
  'WindDir9am',
  'WindDir3pm',
  'WindSpeed9am',
  'WindSpeed3pm',
  'Humidity9am',
  'Humidity3pm',
  'Pressure9am',
  'Pressure3pm',
  'Cloud9am',
  'Cloud3pm',
  'Temp9am',
  'Temp3pm',
  'RainToday'],
 'RainTomorrow')

In [25]:
Main_data = filtered_data[input_columns].copy()
Main_target = filtered_data[target_columns].copy()

In [26]:
Main_data

,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,...,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday
0,Albury,13.4,22.9,0.6,5.468232,7.611178,W,44.0,W,WNW,...,24.0,71.0,22.0,1007.7,1007.1,8.000000,4.50993,16.9,21.8,No
1,Albury,7.4,25.1,0.0,5.468232,7.611178,WNW,44.0,NNW,WSW,...,22.0,44.0,25.0,1010.6,1007.8,4.447461,4.50993,17.2,24.3,No
2,Albury,12.9,25.7,0.0,5.468232,7.611178,WSW,46.0,W,WSW,...,26.0,38.0,30.0,1007.6,1008.7,4.447461,2.00000,21.0,23.2,No
3,Albury,9.2,28.0,0.0,5.468232,7.611178,NE,24.0,SE,E,...,9.0,45.0,16.0,1017.6,1012.8,4.447461,4.50993,18.1,26.5,No
4,Albury,17.5,32.3,1.0,5.468232,7.611178,W,41.0,ENE,NW,...,20.0,82.0,33.0,1010.8,1006.0,7.000000,8.00000,17.8,29.7,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145454,Uluru,3.5,21.8,0.0,5.468232,7.611178,E,31.0,ESE,E,...,13.0,59.0,27.0,1024.7,1021.2,4.447461,4.50993,9.4,20.9,No
145455,Uluru,2.8,23.4,0.0,5.468232,7.611178,E,31.0,SE,ENE,...,11.0,51.0,24.0,1024.6,1020.3,4.447461,4.50993,10.1,22.4,No
145456,Uluru,3.6,25.3,0.0,5.468232,7.611178,NNW,22.0,SE,N,...,9.0,56.0,21.0,1023.5,1019.1,4.447461,4.50993,10.9,24.5,No
145457,Uluru,5.4,26.9,0.0,5.468232,7.611178,N,37.0,SE,WNW,...,9.0,53.0,24.0,1021.0,1016.8,4.447461,4.50993,12.5,26.1,No
145458,Uluru,7.8,27.0,0.0,5.468232,7.611178,SE,28.0,SSE,N,...,7.0,51.0,24.0,1019.4,1016.5,3.000000,2.00000,15.1,26.0,No

In [27]:
import numpy as np
numeric_colms = Main_data.select_dtypes(include = np.number).columns.tolist()
categorical_colms = Main_data.select_dtypes(include = 'object').columns.tolist()

In [28]:
# Now we will use the OneHotEncoder to encode the categorical columns.

In [29]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse_output = False, handle_unknown = 'ignore')

encoder.fit(Main_data[categorical_colms])

OneHotEncoder(handle_unknown='ignore', sparse_output=False)

In [30]:
encoder.categories_

[array(['Adelaide', 'Albany', 'Albury', 'AliceSprings', 'BadgerysCreek',
        'Ballarat', 'Bendigo', 'Brisbane', 'Cairns', 'Canberra', 'Cobar',
        'CoffsHarbour', 'Dartmoor', 'Darwin', 'GoldCoast', 'Hobart',
        'Katherine', 'Launceston', 'Melbourne', 'MelbourneAirport',
        'Mildura', 'Moree', 'MountGambier', 'MountGinini', 'Newcastle',
        'Nhil', 'NorahHead', 'NorfolkIsland', 'Nuriootpa', 'PearceRAAF',
        'Penrith', 'Perth', 'PerthAirport', 'Portland', 'Richmond', 'Sale',
        'SalmonGums', 'Sydney', 'SydneyAirport', 'Townsville',
        'Tuggeranong', 'Uluru', 'WaggaWagga', 'Walpole', 'Watsonia',
        'Williamtown', 'Witchcliffe', 'Wollongong', 'Woomera'],
       dtype=object),
 array(['E', 'ENE', 'ESE', 'N', 'NE', 'NNE', 'NNW', 'NW', 'S', 'SE', 'SSE',
        'SSW', 'SW', 'W', 'WNW', 'WSW', 'unknown'], dtype=object),
 array(['E', 'ENE', 'ESE', 'N', 'NE', 'NNE', 'NNW', 'NW', 'S', 'SE', 'SSE',
        'SSW', 'SW', 'W', 'WNW', 'WSW', 'unknown'], dtype=object),
 array(['E', 'ENE', 'ESE', 'N', 'NE', 'NNE', 'NNW', 'NW', 'S', 'SE', 'SSE',
        'SSW', 'SW', 'W', 'WNW', 'WSW', 'unknown'], dtype=object),
 array(['No', 'Yes'], dtype=object)]

In [31]:
import pandas as pd

encoder_cols = list(encoder.get_feature_names_out(categorical_colms))

encoder_cols

['Location_Adelaide',
 'Location_Albany',
 'Location_Albury',
 'Location_AliceSprings',
 'Location_BadgerysCreek',
 'Location_Ballarat',
 'Location_Bendigo',
 'Location_Brisbane',
 'Location_Cairns',
 'Location_Canberra',
 'Location_Cobar',
 'Location_CoffsHarbour',
 'Location_Dartmoor',
 'Location_Darwin',
 'Location_GoldCoast',
 'Location_Hobart',
 'Location_Katherine',
 'Location_Launceston',
 'Location_Melbourne',
 'Location_MelbourneAirport',
 'Location_Mildura',
 'Location_Moree',
 'Location_MountGambier',
 'Location_MountGinini',
 'Location_Newcastle',
 'Location_Nhil',
 'Location_NorahHead',
 'Location_NorfolkIsland',
 'Location_Nuriootpa',
 'Location_PearceRAAF',
 'Location_Penrith',
 'Location_Perth',
 'Location_PerthAirport',
 'Location_Portland',
 'Location_Richmond',
 'Location_Sale',
 'Location_SalmonGums',
 'Location_Sydney',
 'Location_SydneyAirport',
 'Location_Townsville',
 'Location_Tuggeranong',
 'Location_Uluru',
 'Location_WaggaWagga',
 'Location_Walpole',
 'Location_Watsonia',
 'Location_Williamtown',
 'Location_Witchcliffe',
 'Location_Wollongong',
 'Location_Woomera',
 'WindGustDir_E',
 'WindGustDir_ENE',
 'WindGustDir_ESE',
 'WindGustDir_N',
 'WindGustDir_NE',
 'WindGustDir_NNE',
 'WindGustDir_NNW',
 'WindGustDir_NW',
 'WindGustDir_S',
 'WindGustDir_SE',
 'WindGustDir_SSE',
 'WindGustDir_SSW',
 'WindGustDir_SW',
 'WindGustDir_W',
 'WindGustDir_WNW',
 'WindGustDir_WSW',
 'WindGustDir_unknown',
 'WindDir9am_E',
 'WindDir9am_ENE',
 'WindDir9am_ESE',
 'WindDir9am_N',
 'WindDir9am_NE',
 'WindDir9am_NNE',
 'WindDir9am_NNW',
 'WindDir9am_NW',
 'WindDir9am_S',
 'WindDir9am_SE',
 'WindDir9am_SSE',
 'WindDir9am_SSW',
 'WindDir9am_SW',
 'WindDir9am_W',
 'WindDir9am_WNW',
 'WindDir9am_WSW',
 'WindDir9am_unknown',
 'WindDir3pm_E',
 'WindDir3pm_ENE',
 'WindDir3pm_ESE',
 'WindDir3pm_N',
 'WindDir3pm_NE',
 'WindDir3pm_NNE',
 'WindDir3pm_NNW',
 'WindDir3pm_NW',
 'WindDir3pm_S',
 'WindDir3pm_SE',
 'WindDir3pm_SSE',
 'WindDir3pm_SSW',
 'WindDir3pm_SW',
 'WindDir3pm_W',
 'WindDir3pm_WNW',
 'WindDir3pm_WSW',
 'WindDir3pm_unknown',
 'RainToday_No',
 'RainToday_Yes']

In [32]:
Main_data[encoder_cols] = encoder.transform(Main_data[categorical_colms])

/tmp/ipykernel_3707/318828525.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Main_data[encoder_cols] = encoder.transform(Main_data[categorical_colms])
/tmp/ipykernel_3707/318828525.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Main_data[encoder_cols] = encoder.transform(Main_data[categorical_colms])
/tmp/ipykernel_3707/318828525.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Main_data[encoder_cols] = encoder.transform(Main_data[categorical_colms])
/tmp/ipykernel_3707/318828525.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  Main_data[encoder_cols] = encoder.transform(Main_data[categorical_colms])

In [33]:
Main_data[encoder_cols]

,Location_Adelaide,Location_Albany,Location_Albury,Location_AliceSprings,Location_BadgerysCreek,Location_Ballarat,Location_Bendigo,Location_Brisbane,Location_Cairns,Location_Canberra,...,WindDir3pm_SE,WindDir3pm_SSE,WindDir3pm_SSW,WindDir3pm_SW,WindDir3pm_W,WindDir3pm_WNW,WindDir3pm_WSW,WindDir3pm_unknown,RainToday_No,RainToday_Yes
0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
3,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145454,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
145455,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
145456,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
145457,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
145458,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [34]:
numeric_colms, encoder_cols

(['MinTemp',
  'MaxTemp',
  'Rainfall',
  'Evaporation',
  'Sunshine',
  'WindGustSpeed',
  'WindSpeed9am',
  'WindSpeed3pm',
  'Humidity9am',
  'Humidity3pm',
  'Pressure9am',
  'Pressure3pm',
  'Cloud9am',
  'Cloud3pm',
  'Temp9am',
  'Temp3pm'],
 ['Location_Adelaide',
  'Location_Albany',
  'Location_Albury',
  'Location_AliceSprings',
  'Location_BadgerysCreek',
  'Location_Ballarat',
  'Location_Bendigo',
  'Location_Brisbane',
  'Location_Cairns',
  'Location_Canberra',
  'Location_Cobar',
  'Location_CoffsHarbour',
  'Location_Dartmoor',
  'Location_Darwin',
  'Location_GoldCoast',
  'Location_Hobart',
  'Location_Katherine',
  'Location_Launceston',
  'Location_Melbourne',
  'Location_MelbourneAirport',
  'Location_Mildura',
  'Location_Moree',
  'Location_MountGambier',
  'Location_MountGinini',
  'Location_Newcastle',
  'Location_Nhil',
  'Location_NorahHead',
  'Location_NorfolkIsland',
  'Location_Nuriootpa',
  'Location_PearceRAAF',
  'Location_Penrith',
  'Location_Perth',
  'Location_PerthAirport',
  'Location_Portland',
  'Location_Richmond',
  'Location_Sale',
  'Location_SalmonGums',
  'Location_Sydney',
  'Location_SydneyAirport',
  'Location_Townsville',
  'Location_Tuggeranong',
  'Location_Uluru',
  'Location_WaggaWagga',
  'Location_Walpole',
  'Location_Watsonia',
  'Location_Williamtown',
  'Location_Witchcliffe',
  'Location_Wollongong',
  'Location_Woomera',
  'WindGustDir_E',
  'WindGustDir_ENE',
  'WindGustDir_ESE',
  'WindGustDir_N',
  'WindGustDir_NE',
  'WindGustDir_NNE',
  'WindGustDir_NNW',
  'WindGustDir_NW',
  'WindGustDir_S',
  'WindGustDir_SE',
  'WindGustDir_SSE',
  'WindGustDir_SSW',
  'WindGustDir_SW',
  'WindGustDir_W',
  'WindGustDir_WNW',
  'WindGustDir_WSW',
  'WindGustDir_unknown',
  'WindDir9am_E',
  'WindDir9am_ENE',
  'WindDir9am_ESE',
  'WindDir9am_N',
  'WindDir9am_NE',
  'WindDir9am_NNE',
  'WindDir9am_NNW',
  'WindDir9am_NW',
  'WindDir9am_S',
  'WindDir9am_SE',
  'WindDir9am_SSE',
  'WindDir9am_SSW',
  'WindDir9am_SW',
  'WindDir9am_W',
  'WindDir9am_WNW',
  'WindDir9am_WSW',
  'WindDir9am_unknown',
  'WindDir3pm_E',
  'WindDir3pm_ENE',
  'WindDir3pm_ESE',
  'WindDir3pm_N',
  'WindDir3pm_NE',
  'WindDir3pm_NNE',
  'WindDir3pm_NNW',
  'WindDir3pm_NW',
  'WindDir3pm_S',
  'WindDir3pm_SE',
  'WindDir3pm_SSE',
  'WindDir3pm_SSW',
  'WindDir3pm_SW',
  'WindDir3pm_W',
  'WindDir3pm_WNW',
  'WindDir3pm_WSW',
  'WindDir3pm_unknown',
  'RainToday_No',
  'RainToday_Yes'])

In [35]:
from sklearn.model_selection import train_test_split

splitting_data = Main_data[numeric_colms+encoder_cols].copy()

train_val_dt, test_dt, train_val_target, test_target =  train_test_split(splitting_data, Main_target, random_state=42, test_size = 0.2)

train_data, val_data, train_target, val_target = train_test_split(train_val_dt, train_val_target, test_size=0.25, random_state=42)

In [36]:
train_data

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,...,WindDir3pm_SE,WindDir3pm_SSE,WindDir3pm_SSW,WindDir3pm_SW,WindDir3pm_W,WindDir3pm_WNW,WindDir3pm_WSW,WindDir3pm_unknown,RainToday_No,RainToday_Yes
12319,4.1,21.7,0.0,4.600000,11.300000,31.0,13.0,20.0,53.0,20.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
88560,18.9,30.0,0.0,8.000000,11.100000,30.0,15.0,20.0,54.0,38.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
42526,7.3,18.5,0.2,5.468232,7.611178,26.0,19.0,6.0,94.0,60.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
139212,24.8,35.5,0.0,5.000000,10.400000,46.0,17.0,30.0,80.0,52.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
25223,13.2,32.3,0.0,5.468232,7.611178,22.0,4.0,7.0,72.0,34.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141207,16.0,29.9,0.0,5.000000,11.000000,48.0,20.0,30.0,38.0,17.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
95983,16.8,27.8,0.0,4.400000,7.611178,24.0,0.0,13.0,91.0,58.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
39457,8.5,24.8,0.0,4.800000,7.611178,28.0,19.0,13.0,56.0,24.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
92898,12.7,26.9,0.0,5.468232,7.611178,31.0,15.0,26.0,51.0,58.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
122949,16.7,37.1,0.0,11.200000,13.200000,39.0,15.0,9.0,45.0,19.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [37]:
train_target

12319     No
88560     No
42526     No
139212    No
25223     No
          ..
141207    No
95983     No
39457     No
92898     No
122949    No
Name: RainTomorrow, Length: 84471, dtype: object

In [38]:
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier()

model.fit(train_data, train_target)

DecisionTreeClassifier()

In [39]:
train_predict = model.predict(train_data)

In [40]:
from sklearn.metrics import accuracy_score

train_accuracy = accuracy_score(train_target, train_predict)

print("Accuracy of Train_data: ", train_accuracy*100)

Accuracy of Train_data:  99.99526464703862

In [41]:
# Now lets check for the validation data.

In [42]:
val_predict = model.predict(val_data)

In [43]:
val_accuracy = accuracy_score(val_target, val_predict)

print("Validation_Accuracy : ", val_accuracy*100)


#Our model is performing pretty bad while perforing the model with val_data.

Validation_Accuracy :  79.26699339441721

In [44]:
#Here we are checking the No and Yes that are present in val_target. to compare the performance of our model.

val_target.value_counts()/len(val_target)

# our model is just 1.3% better. (79.25 - 77.612)

RainTomorrow
No     0.77612
Yes    0.22388
Name: count, dtype: float64

In [45]:
#Now lets build another model name-> model_1 and then we will give the parameters like criterian, splitter
#max_depth, max_leaf_nodes, min_samples_split, min_samples_leaf, min_features, min_leaf_nodes, random_state

In [46]:
#Now, to get to know these parameters like max_depth, min_samples_leaf, we need to know theie values.
#So, we can calculate them in that manner
#Lets see the example

In [47]:
#Lets check our models max_depth

max_depth = model.get_depth()

print(max_depth)

# We got 45, so our model has depth of 45.

45

In [48]:
#Now, we can check that where is our model lagging or at which depth point our model is failing.


#for depth in range(1, max_depth):
 # model_1 = DecisionTreeClassifier(criterion='gini', splitter='best', max_depth = depth)
  #model_1.fit(train_data, train_target)

  #train_score = model_1.score(train_data, train_target)
  #val_score = model_1.score(val_data, val_target)

  #print(depth, train_score, val_score)


# Here if you check the output, you can see that after depth=9 the OVERFITTING is started. model is becoming
#dummer after the max_depth of 9. so, we can keep the max_depth of 9 to make GOOD MODEL

In [49]:
# WE CAN ALSO USE ANOTHER METHOD CALLED "cross_val_score"
#from sklearn.model_selection import cross_val_score
#from sklearn.tree import DecisionTreeClassifier

#for depth in [2, 3, 4, 5, 6, 8, 10, 12]:

 #   model = DecisionTreeClassifier(
  #      max_depth=depth,
   #     random_state=42
    #)

   # scores = cross_val_score(
    #    model,
     #   X_train,
      #  y_train,
       # cv=5
    #)

    #print(
     #   depth,
      #  scores.mean()
    #)

In [50]:
#There is an even better way: GridSearchCV

#Eventually, you don't have to manually test every combination.

#You can tell sklearn:

#"Try these different parameters and find the configuration with the best cross-validation score."

#For example:

#from sklearn.model_selection import GridSearchCV
#from sklearn.tree import DecisionTreeClassifier

#model = DecisionTreeClassifier(
#    random_state=42
#)

#param_grid = {
#    "max_depth": [2, 3, 4, 5, 6, 8, 10],
#    "min_samples_split": [2, 5, 10],
#    "min_samples_leaf": [1, 2, 5]
#}

#grid = GridSearchCV(
#    model,
#    param_grid,
#    cv=5,
#    scoring="accuracy"
#)

#grid.fit(X_train, y_train)

#print(grid.best_params_)

#might give:

#{
#    'max_depth': 5,
#    'min_samples_leaf': 2,
#    'min_samples_split': 5
#}

In [58]:
# Lets check the best value for min_samples_split

for sample in [ 30,40,50,60, 70, 80, 85, 90, 95, 100, 105,110,115, 120, 125, 130, 135, 140, 145, 150, 155, 160]:
  model_2 = DecisionTreeClassifier(criterion='gini', splitter='best', max_depth = 9 ,min_samples_split=sample)
  model_2.fit(train_data, train_target)

  train_dt_score = model_2.score(train_data, train_target)
  val_dt_score = model_2.score(val_data, val_target)
  test_dt_score = model_2.score(test_dt, test_target)


  print(sample, train_dt_score, val_dt_score, test_dt_score)


  #Hence, we are getting good score at "min_sample_split = 115", from 116 it is decreasing the efficency.

90 0.8583655929253827 0.8431351658498473 0.8392996661694723
95 0.858235370718945 0.8430996519639179 0.8394417217131899
100 0.8579749263060695 0.8432061936217061 0.8394062078272605
105 0.857821027334825 0.8430286241920592 0.8392996661694723
110 0.8576789667459839 0.8429220825342709 0.839370693941331
115 0.8575132293923359 0.8427800269905533 0.839370693941331
120 0.8572764617442673 0.8426024575609063 0.8389090134242488
125 0.8570396940961987 0.8424959159031181 0.8385538745649549
130 0.856909471889761 0.8423893742453299 0.8384828467930961
135 0.8567792496833233 0.8423893742453299 0.8384473329071667
140 0.8565188052704479 0.8423183464734711 0.8380921940478727
145 0.8564596133584307 0.8426734853327651 0.8382342495915903
150 0.8564240982112205 0.8426024575609063 0.838198735705661
155 0.8564359365936238 0.8425669436749769 0.8381632218197315
160 0.8558676942382593 0.8420697492719653 0.8378791107322964

In [ ]:
# Now we will check min_samples_leaf. by managing this hyperparameter, we can achieve a better model

In [60]:
 for leaf in [2,5,10,15,20,22,25,29,30,35,40,45,50,55,60,65,70,75,80]:

  model_3 = DecisionTreeClassifier(criterion = 'gini', splitter='best', min_samples_leaf=leaf)
  model_3.fit(train_data, train_target)

  train_dt_dt_score = model_3.score(train_data, train_target)
  val_dt_dt_score = model_3.score(val_data, val_target)

  print(leaf, train_dt_dt_score, val_dt_dt_score)

  # We have our best model at "min_samples_leaf = 50". at leaf_splitting of 50

2 0.970072569284133 0.8001988777612047
5 0.92486178688544 0.8077278215782371
10 0.894602881462277 0.8258754172881597
15 0.8823738324395355 0.8291426947936643
20 0.8749038131429722 0.8333688472192627
22 0.872855772987179 0.8339370693941331
25 0.8707603793017722 0.8336529583066979
29 0.8678836523777391 0.8356417359187442
30 0.8671141575215162 0.8367071524966262
35 0.8644386830983415 0.8361744442076852
40 0.8622367439713038 0.8401164855458484
45 0.8605320169052101 0.8395837772569075
50 0.8592061180760261 0.8408977910362951
55 0.8583064010133655 0.8403295688614248
60 0.8573356536562844 0.8400454577739896
65 0.8567082193889027 0.8399744300021308
70 0.8557137952670147 0.8408622771503658
75 0.8554059973245256 0.8403295688614248
80 0.8549561387931953 0.8402940549754954

In [ ]:
# NOW LETS CREATE THE BEST MODEL. BY USING ALL THE HYPERPARAMETERS THAT WE FOUND.

In [62]:
Best_Model = DecisionTreeClassifier(
    criterion = 'gini',
    splitter = 'best',
    max_depth = 9,
    min_samples_split = 115,
    min_samples_leaf = 50,
    random_state = 42
)

Best_Model.fit(train_data, train_target)

Best_Prediction = Best_Model.predict(train_data)

In [69]:
Best_accuracy = accuracy_score(train_target, Best_Prediction)

print("Best_train_dt_accuracy: ", Best_accuracy*100)

Best_train_dt_accuracy:  85.50626842348261

In [ ]:
# Now we will predict Validation data and next test data

In [70]:
Best_Val_Prediction = Best_Model.predict(val_data)

Best_val_accuracy = accuracy_score(val_target, Best_Val_Prediction)

print("Best_Validation_Prediction: ", Best_val_accuracy*100)

Best_Validation_Prediction:  84.24604020171887

In [ ]:
# Now we will predict the Test data

In [71]:
Best_Test_Prediction = Best_Model.predict(test_dt)

Best_test_accuracy = accuracy_score(test_target, Best_Test_Prediction)

print("Best_Test_dt_Accuracy: ", Best_test_accuracy*100)

Best_Test_dt_Accuracy:  84.10043326940834

In [ ]:
# Now see our train_data, val_data, test_data are accurate!!
# train_prediction = 85.506%
# validation_prediction = 84.246%
#Test_prediction = 84.100%

#Hence, If we improve Hyper Parameters, then we can decrease "Overfitting" and we can make "Best Model"