<a href="https://colab.research.google.com/github/Siva1212-genious/ML-Algorithms---ScikitLearn/blob/main/LogesticRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install legacy-cgi --quiet

In [ ]:
!pip install opendatasets --quiet

In [ ]:
import opendatasets as od

dataset_url = 'https://www.kaggle.com/jsphyg/weather-dataset-rattle-package'

od.download(dataset_url)

In [ ]:
import os

data_dir = './weather-dataset-rattle-package'

os.listdir(data_dir)

In [ ]:
data = data_dir + '/weatherAUS.csv'

In [ ]:
import pandas as pd

raw_df = pd.read_csv(data)

raw_df

In [ ]:
#First lets drop the unknown columns in RainToday and RainTommorow columns

In [ ]:
raw_df.dropna(subset = ['RainToday', 'RainTomorrow'], inplace = True)

In [ ]:
raw_df.info()

In [ ]:
#Now let us identify the numeric columns and categorical columns in our whole dataset and we will clear them

In [ ]:
import numpy as np
#numerical columns

numerical_columns = raw_df.select_dtypes(include = np.number).columns.tolist()

In [ ]:
numerical_columns

In [ ]:
#categorical columns

categorical_columns = raw_df.select_dtypes('object').columns.tolist()

categorical_columns

In [ ]:
# Now lets use imputer technique and replace the null values present in numerical columns

In [ ]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy = 'mean')

raw_df[numerical_columns] = imputer.fit_transform(raw_df[numerical_columns])

In [ ]:
#checking if the null values present in the numerical columns

raw_df[numerical_columns].isna().sum()

In [ ]:
#Now lets purify the categorical columns

In [ ]:
raw_df[categorical_columns] = raw_df[categorical_columns].fillna('unknown')

In [ ]:
#checking if the null values presentin categorical columns

In [ ]:
raw_df[categorical_columns].isna().sum()

In [ ]:
raw_df.value_counts('RainToday')

In [ ]:
#Now lets seperate the input_columns and target_columns

In [ ]:
input_columns = list(raw_df.columns)[1:-1]

In [ ]:
input_cols = raw_df[input_columns]
target_cols = raw_df['RainTomorrow']

In [ ]:
#Now our data Set is clear for our Model Implementation. Now we need to scalarize the numerical Columns and Encode the Categorical values to make the best fit for our model

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

scaler.fit(input_cols[numerical_columns])

In [ ]:
list(scaler.data_min_)

In [ ]:
list(scaler.data_max_)

In [ ]:
input_cols[numerical_columns] = scaler.transform(input_cols[numerical_columns])

In [ ]:
input_cols[numerical_columns].describe()

In [ ]:
#We will do the encoding for categorical Columns of inputs_column

In [ ]:
categorical_columns = input_cols.select_dtypes('object').columns.tolist()

In [ ]:
input_cols[categorical_columns].info()

In [ ]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse_output = False, handle_unknown = 'ignore')

encoder.fit(input_cols[categorical_columns])

In [ ]:
encoder.categories_

In [ ]:
#Now we will create names for these new columns using get_feature_names function.

In [ ]:
encoded_cols = list(encoder.get_feature_names_out(categorical_columns))

In [ ]:
encoded_cols

In [ ]:
input_cols[encoded_cols] = encoder.transform(input_cols[categorical_columns])

/tmp/ipykernel_3926/766166252.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  input_cols[encoded_cols] = encoder.transform(input_cols[categorical_columns])
/tmp/ipykernel_3926/766166252.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  input_cols[encoded_cols] = encoder.transform(input_cols[categorical_columns])
/tmp/ipykernel_3926/766166252.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  input_cols[encoded_cols] = encoder.transform(input_cols[categorical_columns])
/tmp/ipykernel_3926/766166252.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  input_cols[encoded_cols] = encoder.transform(input_cols[categorical_columns])
/tmp/ipykernel_3926/766166252.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  input_cols[encoded_cols] = encoder.transform(input_cols[categorical_columns])
/tmp/ipykernel_3926/766166252.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  input_cols[encoded_cols] = encoder.transform(input_cols[categorical_columns])
/tmp/ipykernel_3926/766166252.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  input_cols[encoded_cols] = encoder.transform(input_cols[categorical_columns])
/tmp/ipykernel_3926/766166252.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  input_cols[encoded_cols] = encoder.transform(input_cols[categorical_columns])
/tmp/ipykernel_3926/766166252.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  input_cols[encoded_cols] = encoder.transform(input_cols[categorical_columns])
/tmp/ipykernel_3926/766166252.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  input_cols[encoded_cols] = encoder.transform(input_cols[categorical_columns])
/tmp/ipykernel_3926/766166252.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  input_cols[encoded_cols] = encoder.transform(input_cols[categorical_columns])
/tmp/ipykernel_3926/766166252.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  input_cols[encoded_cols] = encoder.transform(input_cols[categorical_columns])
/tmp/ipykernel_3926/766166252.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  input_cols[encoded_cols] = encoder.transform(input_cols[categorical_columns])
/tmp/ipykernel_3926/766166252.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  input_cols[encoded_cols] = encoder.transform(input_cols[categorical_columns])
/tmp/ipykernel_3926/766166252.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  input_cols[encoded_cols] = encoder.transform(input_cols[categorical_columns])
/tmp/ipykernel_3926/766166252.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  input_cols[encoded_cols] = encoder.transform(input_cols[categorical_columns])
/tmp/ipykernel_3926/766166252.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  input_cols[encoded_cols] = encoder.transform(input_cols[categorical_columns])
/tmp/ipykernel_3926/766166252.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  input_cols[encoded_cols] = encoder.transform(input_cols[categorical_columns])
/tmp/ipykernel_3926/766166252.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  input_cols[encoded_cols] = encoder.transform(input_cols[categorical_columns])
/tmp/ipykernel_3926/766166252.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  input_cols[encoded_cols] = encoder.transform(input_cols[categorical_columns])
/tmp/ipykernel_3926/766166252.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  input_cols[encoded_cols] = encoder.transform(input_cols[categorical_columns])
/tmp/ipykernel_3926/766166252.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  input_cols[encoded_cols] = encoder.transform(input_cols[categorical_columns])
/tmp/ipykernel_3926/766166252.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  input_cols[encoded_cols] = encoder.transform(input_cols[categorical_columns])
/tmp/ipykernel_3926/766166252.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  input_cols[encoded_cols] = encoder.transform(input_cols[categorical_columns])

In [ ]:
input_cols.columns.to_list()

['Location',
 'MinTemp',
 'MaxTemp',
 'Rainfall',
 'Evaporation',
 'Sunshine',
 'WindGustDir',
 'WindGustSpeed',
 'WindDir9am',
 'WindDir3pm',
 'WindSpeed9am',
 'WindSpeed3pm',
 'Humidity9am',
 'Humidity3pm',
 'Pressure9am',
 'Pressure3pm',
 'Cloud9am',
 'Cloud3pm',
 'Temp9am',
 'Temp3pm',
 'RainToday',
 'Location_Adelaide',
 'Location_Albany',
 'Location_Albury',
 'Location_AliceSprings',
 'Location_BadgerysCreek',
 'Location_Ballarat',
 'Location_Bendigo',
 'Location_Brisbane',
 'Location_Cairns',
 'Location_Canberra',
 'Location_Cobar',
 'Location_CoffsHarbour',
 'Location_Dartmoor',
 'Location_Darwin',
 'Location_GoldCoast',
 'Location_Hobart',
 'Location_Katherine',
 'Location_Launceston',
 'Location_Melbourne',
 'Location_MelbourneAirport',
 'Location_Mildura',
 'Location_Moree',
 'Location_MountGambier',
 'Location_MountGinini',
 'Location_Newcastle',
 'Location_Nhil',
 'Location_NorahHead',
 'Location_NorfolkIsland',
 'Location_Nuriootpa',
 'Location_PearceRAAF',
 'Location_Penrith',
 'Location_Perth',
 'Location_PerthAirport',
 'Location_Portland',
 'Location_Richmond',
 'Location_Sale',
 'Location_SalmonGums',
 'Location_Sydney',
 'Location_SydneyAirport',
 'Location_Townsville',
 'Location_Tuggeranong',
 'Location_Uluru',
 'Location_WaggaWagga',
 'Location_Walpole',
 'Location_Watsonia',
 'Location_Williamtown',
 'Location_Witchcliffe',
 'Location_Wollongong',
 'Location_Woomera',
 'WindGustDir_E',
 'WindGustDir_ENE',
 'WindGustDir_ESE',
 'WindGustDir_N',
 'WindGustDir_NE',
 'WindGustDir_NNE',
 'WindGustDir_NNW',
 'WindGustDir_NW',
 'WindGustDir_S',
 'WindGustDir_SE',
 'WindGustDir_SSE',
 'WindGustDir_SSW',
 'WindGustDir_SW',
 'WindGustDir_W',
 'WindGustDir_WNW',
 'WindGustDir_WSW',
 'WindGustDir_unknown',
 'WindDir9am_E',
 'WindDir9am_ENE',
 'WindDir9am_ESE',
 'WindDir9am_N',
 'WindDir9am_NE',
 'WindDir9am_NNE',
 'WindDir9am_NNW',
 'WindDir9am_NW',
 'WindDir9am_S',
 'WindDir9am_SE',
 'WindDir9am_SSE',
 'WindDir9am_SSW',
 'WindDir9am_SW',
 'WindDir9am_W',
 'WindDir9am_WNW',
 'WindDir9am_WSW',
 'WindDir9am_unknown',
 'WindDir3pm_E',
 'WindDir3pm_ENE',
 'WindDir3pm_ESE',
 'WindDir3pm_N',
 'WindDir3pm_NE',
 'WindDir3pm_NNE',
 'WindDir3pm_NNW',
 'WindDir3pm_NW',
 'WindDir3pm_S',
 'WindDir3pm_SE',
 'WindDir3pm_SSE',
 'WindDir3pm_SSW',
 'WindDir3pm_SW',
 'WindDir3pm_W',
 'WindDir3pm_WNW',
 'WindDir3pm_WSW',
 'WindDir3pm_unknown',
 'RainToday_No',
 'RainToday_Yes']

In [ ]:
#We have a dataset that contains oldcolumns and new columns. now lets make a perfect dataset for out model.
#by adding the encoded_cols + numerical_columns. because, we need to remove the duplicates

In [ ]:
Main_input_columns = input_cols[numerical_columns+encoded_cols]

In [ ]:
Main_input_columns

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,...,WindDir3pm_SE,WindDir3pm_SSE,WindDir3pm_SSW,WindDir3pm_SW,WindDir3pm_W,WindDir3pm_WNW,WindDir3pm_WSW,WindDir3pm_unknown,RainToday_No,RainToday_Yes
0,0.516509,0.523629,0.001617,0.037741,0.526244,0.294574,0.153846,0.275862,0.71,0.22,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
1,0.375000,0.565217,0.000000,0.037741,0.526244,0.294574,0.030769,0.252874,0.44,0.25,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
2,0.504717,0.576560,0.000000,0.037741,0.526244,0.310078,0.146154,0.298851,0.38,0.30,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
3,0.417453,0.620038,0.000000,0.037741,0.526244,0.139535,0.084615,0.103448,0.45,0.16,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.613208,0.701323,0.002695,0.037741,0.526244,0.271318,0.053846,0.229885,0.82,0.33,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145454,0.283019,0.502836,0.000000,0.037741,0.526244,0.193798,0.115385,0.149425,0.59,0.27,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
145455,0.266509,0.533081,0.000000,0.037741,0.526244,0.193798,0.100000,0.126437,0.51,0.24,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
145456,0.285377,0.568998,0.000000,0.037741,0.526244,0.124031,0.100000,0.103448,0.56,0.21,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
145457,0.327830,0.599244,0.000000,0.037741,0.526244,0.240310,0.069231,0.103448,0.53,0.24,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
145458,0.384434,0.601134,0.000000,0.037741,0.526244,0.170543,0.100000,0.080460,0.51,0.24,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [ ]:
#Now Let Us split the data for training_set, validation_set, test_set and we will design our model

In [ ]:
from sklearn.model_selection import train_test_split

train_val_input, test_input, train_val_target, test_target = train_test_split(Main_input_columns, target_cols ,test_size=0.2, random_state = 32)

In [ ]:
#Now Let us split the validation and train inputs

train_input, val_input, train_target, val_target  = train_test_split(train_val_input, train_val_target, test_size = 0.25, random_state=32)

In [ ]:
print(train_input.shape)
print(val_input.shape)
print(test_input.shape)
print(train_target.shape)
print(val_target.shape)
print(test_target.shape)

(84471, 118)
(28158, 118)
(28158, 118)
(84471,)
(28158,)
(28158,)

In [ ]:
#Till Here our DATA PREPROCESSING HAS COMPLETED. NOW, LETS TRAIN THE MODEL.

In [ ]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(train_input, train_target)

LogisticRegression()

In [ ]:
train_predict = model.predict(train_input)

train_predict

array(['No', 'No', 'No', ..., 'No', 'No', 'No'], dtype=object)

In [ ]:
train_target

34429      No
140370     No
103023     No
21676      No
93342     Yes
         ...
106331     No
90494      No
136742     No
97405      No
91525      No
Name: RainTomorrow, Length: 84471, dtype: object

In [ ]:
#Now, lets see how confident my model is

In [ ]:
train_predict_proba = model.predict_proba(train_input)

In [ ]:
train_predict_proba

array([[0.9938831 , 0.0061169 ],
       [0.86508962, 0.13491038],
       [0.98493688, 0.01506312],
       ...,
       [0.98801792, 0.01198208],
       [0.96022861, 0.03977139],
       [0.96160448, 0.03839552]])