<a href="https://colab.research.google.com/github/Siva1212-genious/ML-Algorithms---ScikitLearn/blob/main/LogisticRegression_main.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install legacy-cgi --quiet

In [2]:
!pip install opendatasets --quiet

In [3]:
import opendatasets as od

dataset_url = 'https://www.kaggle.com/datasets/uciml/breast-cancer-wisconsin-data'

od.download(dataset_url)

Please provide your Kaggle credentials to download this dataset. Learn more: http://bit.ly/kaggle-creds
Your Kaggle username: siva
Your Kaggle Key: ··········
Dataset URL: https://www.kaggle.com/datasets/uciml/breast-cancer-wisconsin-data
Downloading breast-cancer-wisconsin-data.zip to ./breast-cancer-wisconsin-data

100%|██████████| 48.6k/48.6k [00:00<00:00, 42.5MB/s]

In [4]:
import os

data_set = './breast-cancer-wisconsin-data'

os.listdir(data_set)

['data.csv']

In [5]:
data = data_set + '/data.csv'

data

'./breast-cancer-wisconsin-data/data.csv'

In [6]:
import pandas as pd

raw_data = pd.read_csv(data)

raw_data

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,...,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,NaN
565,926682,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,...,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,NaN
566,926954,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,...,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,NaN
567,927241,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,...,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,NaN
568,92751,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,...,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039,NaN

In [7]:
raw_data[1:50]

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
1,842517,M,20.570,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.070170,...,23.41,158.80,1956.0,0.12380,0.18660,0.24160,0.18600,0.2750,0.08902,NaN
2,84300903,M,19.690,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.127900,...,25.53,152.50,1709.0,0.14440,0.42450,0.45040,0.24300,0.3613,0.08758,NaN
3,84348301,M,11.420,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.105200,...,26.50,98.87,567.7,0.20980,0.86630,0.68690,0.25750,0.6638,0.17300,NaN
4,84358402,M,20.290,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.104300,...,16.67,152.20,1575.0,0.13740,0.20500,0.40000,0.16250,0.2364,0.07678,NaN
5,843786,M,12.450,15.70,82.57,477.1,0.12780,0.17000,0.15780,0.080890,...,23.75,103.40,741.6,0.17910,0.52490,0.53550,0.17410,0.3985,0.12440,NaN
6,844359,M,18.250,19.98,119.60,1040.0,0.09463,0.10900,0.11270,0.074000,...,27.66,153.20,1606.0,0.14420,0.25760,0.37840,0.19320,0.3063,0.08368,NaN
7,84458202,M,13.710,20.83,90.20,577.9,0.11890,0.16450,0.09366,0.059850,...,28.14,110.60,897.0,0.16540,0.36820,0.26780,0.15560,0.3196,0.11510,NaN
8,844981,M,13.000,21.82,87.50,519.8,0.12730,0.19320,0.18590,0.093530,...,30.73,106.20,739.3,0.17030,0.54010,0.53900,0.20600,0.4378,0.10720,NaN
9,84501001,M,12.460,24.04,83.97,475.9,0.11860,0.23960,0.22730,0.085430,...,40.68,97.65,711.4,0.18530,1.05800,1.10500,0.22100,0.4366,0.20750,NaN
10,845636,M,16.020,23.24,102.70,797.8,0.08206,0.06669,0.03299,0.033230,...,33.88,123.80,1150.0,0.11810,0.15510,0.14590,0.09975,0.2948,0.08452,NaN
11,84610002,M,15.780,17.89,103.60,781.0,0.09710,0.12920,0.09954,0.066060,...,27.28,136.50,1299.0,0.13960,0.56090,0.39650,0.18100,0.3792,0.10480,NaN
12,846226,M,19.170,24.80,132.40,1123.0,0.09740,0.24580,0.20650,0.111800,...,29.94,151.70,1332.0,0.10370,0.39030,0.36390,0.17670,0.3176,0.10230,NaN
13,846381,M,15.850,23.95,103.70,782.7,0.08401,0.10020,0.09938,0.053640,...,27.66,112.00,876.5,0.11310,0.19240,0.23220,0.11190,0.2809,0.06287,NaN
14,84667401,M,13.730,22.61,93.60,578.3,0.11310,0.22930,0.21280,0.080250,...,32.01,108.80,697.7,0.16510,0.77250,0.69430,0.22080,0.3596,0.14310,NaN
15,84799002,M,14.540,27.54,96.73,658.8,0.11390,0.15950,0.16390,0.073640,...,37.13,124.10,943.2,0.16780,0.65770,0.70260,0.17120,0.4218,0.13410,NaN
16,848406,M,14.680,20.13,94.74,684.5,0.09867,0.07200,0.07395,0.052590,...,30.88,123.40,1138.0,0.14640,0.18710,0.29140,0.16090,0.3029,0.08216,NaN
17,84862001,M,16.130,20.68,108.10,798.8,0.11700,0.20220,0.17220,0.102800,...,31.48,136.80,1315.0,0.17890,0.42330,0.47840,0.20730,0.3706,0.11420,NaN
18,849014,M,19.810,22.15,130.00,1260.0,0.09831,0.10270,0.14790,0.094980,...,30.88,186.80,2398.0,0.15120,0.31500,0.53720,0.23880,0.2768,0.07615,NaN
19,8510426,B,13.540,14.36,87.46,566.3,0.09779,0.08129,0.06664,0.047810,...,19.26,99.70,711.2,0.14400,0.17730,0.23900,0.12880,0.2977,0.07259,NaN
20,8510653,B,13.080,15.71,85.63,520.0,0.10750,0.12700,0.04568,0.031100,...,20.49,96.09,630.5,0.13120,0.27760,0.18900,0.07283,0.3184,0.08183,NaN
21,8510824,B,9.504,12.44,60.34,273.9,0.10240,0.06492,0.02956,0.020760,...,15.66,65.13,314.9,0.13240,0.11480,0.08867,0.06227,0.2450,0.07773,NaN
22,8511133,M,15.340,14.26,102.50,704.4,0.10730,0.21350,0.20770,0.097560,...,19.08,125.10,980.9,0.13900,0.59540,0.63050,0.23930,0.4667,0.09946,NaN
23,851509,M,21.160,23.04,137.20,1404.0,0.09428,0.10220,0.10970,0.086320,...,35.59,188.00,2615.0,0.14010,0.26000,0.31550,0.20090,0.2822,0.07526,NaN
24,852552,M,16.650,21.38,110.00,904.6,0.11210,0.14570,0.15250,0.091700,...,31.56,177.00,2215.0,0.18050,0.35780,0.46950,0.20950,0.3613,0.09564,NaN
25,852631,M,17.140,16.40,116.00,912.7,0.11860,0.22760,0.22290,0.140100,...,21.40,152.40,1461.0,0.15450,0.39490,0.38530,0.25500,0.4066,0.10590,NaN
26,852763,M,14.580,21.53,97.41,644.8,0.10540,0.18680,0.14250,0.087830,...,33.21,122.40,896.9,0.15250,0.66430,0.55390,0.27010,0.4264,0.12750,NaN
27,852781,M,18.610,20.25,122.10,1094.0,0.09440,0.10660,0.14900,0.077310,...,27.26,139.90,1403.0,0.13380,0.21170,0.34460,0.14900,0.2341,0.07421,NaN
28,852973,M,15.300,25.27,102.40,732.4,0.10820,0.16970,0.16830,0.087510,...,36.71,149.30,1269.0,0.16410,0.61100,0.63350,0.20240,0.4027,0.09876,NaN
29,853201,M,17.570,15.05,115.00,955.1,0.09847,0.11570,0.09875,0.079530,...,19.52,134.90,1227.0,0.12550,0.28120,0.24890,0.14560,0.2756,0.07919,NaN
30,853401,M,18.630,25.11,124.80,1088.0,0.10640,0.18870,0.23190,0.124400,...,34.01,160.50,1670.0,0.14910,0.42570,0.61330,0.18480,0.3444,0.09782,NaN
31,853612,M,11.840,18.70,77.93,440.6,0.11090,0.15160,0.12180,0.051820,...,28.12,119.40,888.7,0.16370,0.57750,0.69560,0.15460,0.4761,0.14020,NaN
32,85382601,M,17.020,23.98,112.80,899.3,0.11970,0.14960,0.24170,0.120300,...,32.09,136.10,1344.0,0.16340,0.35590,0.55880,0.18470,0.3530,0.08482,NaN
33,854002,M,19.270,26.47,127.90,1162.0,0.09401,0.17190,0.16570,0.075930,...,30.90,161.40,1813.0,0.15090,0.65900,0.60910,0.17850,0.3672,0.11230,NaN
34,854039,M,16.130,17.88,107.00,807.2,0.10400,0.15590,0.13540,0.077520,...,27.26,132.70,1261.0,0.14460,0.58040,0.52740,0.18640,0.4270,0.12330,NaN
35,854253,M,16.740,21.59,110.10,869.5,0.09610,0.13360,0.13480,0.060180,...,29.02,133.50,1229.0,0.15630,0.38350,0.54090,0.18130,0.4863,0.08633,NaN
36,854268,M,14.250,21.72,93.63,633.0,0.09823,0.10980,0.13190,0.055980,...,30.36,116.20,799.6,0.14460,0.42380,0.51860,0.14470,0.3591,0.10140,NaN
37,854941,B,13.030,18.42,82.61,523.8,0.08983,0.03766,0.02562,0.029230,...,22.81,84.46,545.9,0.09701,0.04619,0.04833,0.05013,0.1987,0.06169,NaN
38,855133,M,14.990,25.20,95.54,698.8,0.09387,0.05131,0.02398,0.028990,...,25.20,95.54,698.8,0.09387,0.05131,0.02398,0.02899,0.1565,0.05504,NaN
39,855138,M,13.480,20.82,88.40,559.2,0.10160,0.12550,0.10630,0.054390,...,26.02,107.30,740.4,0.16100,0.42250,0.50300,0.22580,0.2807,0.10710,NaN
40,855167,M,13.440,21.58,86.18,563.0,0.08162,0.06031,0.03110,0.020310,...,30.25,102.50,787.9,0.10940,0.20430,0.20850,0.11120,0.2994,0.07146,NaN
41,855563,M,10.950,21.35,71.90,371.1,0.12270,0.12180,0.10440,0.056690,...,35.34,87.22,514.0,0.19090,0.26980,0.40230,0.14240,0.2964,0.09606,NaN
42,855625,M,19.070,24.81,128.30,1104.0,0.09081,0.21900,0.21070,0.099610,...,33.17,177.40,1651.0,0.12470,0.74440,0.72420,0.24930,0.4670,0.10380,NaN
43,856106,M,13.280,20.28,87.32,545.2,0.10410,0.14360,0.09847,0.061580,...,28.00,113.10,907.2,0.15300,0.37240,0.36640,0.14920,0.3739,0.10270,NaN
44,85638502,M,13.170,21.81,85.42,531.5,0.09714,0.10470,0.08259,0.052520,...,29.89,105.50,740.7,0.15030,0.39040,0.37280,0.16070,0.3693,0.09618,NaN
45,857010,M,18.650,17.60,123.70,1076.0,0.10990,0.16860,0.19740,0.100900,...,21.32,150.60,1567.0,0.16790,0.50900,0.73450,0.23780,0.3799,0.09185,NaN
46,85713702,B,8.196,16.84,51.71,201.9,0.08600,0.05943,0.01588,0.005917,...,21.96,57.26,242.2,0.12970,0.13570,0.06880,0.02564,0.3105,0.07409,NaN
47,85715,M,13.170,18.66,85.98,534.6,0.11580,0.12310,0.12260,0.073400,...,27.95,102.80,759.4,0.17860,0.41660,0.50060,0.20880,0.3900,0.11790,NaN
48,857155,B,12.050,14.63,78.04,449.3,0.10310,0.09092,0.06592,0.027490,...,20.70,89.88,582.6,0.14940,0.21560,0.30500,0.06548,0.2747,0.08301,NaN
49,857156,B,13.490,22.30,86.91,561.0,0.08752,0.07698,0.04751,0.033840,...,31.82,99.00,698.8,0.11620,0.17110,0.22820,0.12820,0.2871,0.06917,NaN

In [8]:
raw_data.isna().sum()

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed: 32                569
dtype: int64

In [9]:
raw_data.describe()

,id,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
count,5.690000e+02,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,...,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,0.0
mean,3.037183e+07,14.127292,19.289649,91.969033,654.889104,0.096360,0.104341,0.088799,0.048919,0.181162,...,25.677223,107.261213,880.583128,0.132369,0.254265,0.272188,0.114606,0.290076,0.083946,NaN
std,1.250206e+08,3.524049,4.301036,24.298981,351.914129,0.014064,0.052813,0.079720,0.038803,0.027414,...,6.146258,33.602542,569.356993,0.022832,0.157336,0.208624,0.065732,0.061867,0.018061,NaN
min,8.670000e+03,6.981000,9.710000,43.790000,143.500000,0.052630,0.019380,0.000000,0.000000,0.106000,...,12.020000,50.410000,185.200000,0.071170,0.027290,0.000000,0.000000,0.156500,0.055040,NaN
25%,8.692180e+05,11.700000,16.170000,75.170000,420.300000,0.086370,0.064920,0.029560,0.020310,0.161900,...,21.080000,84.110000,515.300000,0.116600,0.147200,0.114500,0.064930,0.250400,0.071460,NaN
50%,9.060240e+05,13.370000,18.840000,86.240000,551.100000,0.095870,0.092630,0.061540,0.033500,0.179200,...,25.410000,97.660000,686.500000,0.131300,0.211900,0.226700,0.099930,0.282200,0.080040,NaN
75%,8.813129e+06,15.780000,21.800000,104.100000,782.700000,0.105300,0.130400,0.130700,0.074000,0.195700,...,29.720000,125.400000,1084.000000,0.146000,0.339100,0.382900,0.161400,0.317900,0.092080,NaN
max,9.113205e+08,28.110000,39.280000,188.500000,2501.000000,0.163400,0.345400,0.426800,0.201200,0.304000,...,49.540000,251.200000,4254.000000,0.222600,1.058000,1.252000,0.291000,0.663800,0.207500,NaN

In [10]:
#Now lets remove unusefull columns
raw_data.drop(columns = ['Unnamed: 32'], inplace = True)

In [11]:
raw_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       569 non-null    int64
 1   diagnosis                569 non-null    object
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             569 non-null    float64
 15  area_se                  569 non-null    float64
 16  smoothness_se            569 non-null    float64
 17  compactness_se           569 non-null    float64
 18  concavity_se             569 non-null    float64
 19  concave points_se        569 non-null    float64
 20  symmetry_se              569 non-null    float64
 21  fractal_dimension_se     569 non-null    float64
 22  radius_worst             569 non-null    float64
 23  texture_worst            569 non-null    float64
 24  perimeter_worst          569 non-null    float64
 25  area_worst               569 non-null    float64
 26  smoothness_worst         569 non-null    float64
 27  compactness_worst        569 non-null    float64
 28  concavity_worst          569 non-null    float64
 29  concave points_worst     569 non-null    float64
 30  symmetry_worst           569 non-null    float64
 31  fractal_dimension_worst  569 non-null    float64
dtypes: float64(30), int64(1), object(1)
memory usage: 142.4+ KB

In [12]:
#Now lets do the scalling for all the input columns using MinMaxScalar

In [13]:
#Lets first choose the numeric columns
import numpy as np

numeric_columns = raw_data.select_dtypes(include = np.number).columns.tolist()

In [14]:
numeric_columns

['id',
 'radius_mean',
 'texture_mean',
 'perimeter_mean',
 'area_mean',
 'smoothness_mean',
 'compactness_mean',
 'concavity_mean',
 'concave points_mean',
 'symmetry_mean',
 'fractal_dimension_mean',
 'radius_se',
 'texture_se',
 'perimeter_se',
 'area_se',
 'smoothness_se',
 'compactness_se',
 'concavity_se',
 'concave points_se',
 'symmetry_se',
 'fractal_dimension_se',
 'radius_worst',
 'texture_worst',
 'perimeter_worst',
 'area_worst',
 'smoothness_worst',
 'compactness_worst',
 'concavity_worst',
 'concave points_worst',
 'symmetry_worst',
 'fractal_dimension_worst']

In [15]:
numeric_columns = numeric_columns[1:]

In [16]:
numeric_columns

['radius_mean',
 'texture_mean',
 'perimeter_mean',
 'area_mean',
 'smoothness_mean',
 'compactness_mean',
 'concavity_mean',
 'concave points_mean',
 'symmetry_mean',
 'fractal_dimension_mean',
 'radius_se',
 'texture_se',
 'perimeter_se',
 'area_se',
 'smoothness_se',
 'compactness_se',
 'concavity_se',
 'concave points_se',
 'symmetry_se',
 'fractal_dimension_se',
 'radius_worst',
 'texture_worst',
 'perimeter_worst',
 'area_worst',
 'smoothness_worst',
 'compactness_worst',
 'concavity_worst',
 'concave points_worst',
 'symmetry_worst',
 'fractal_dimension_worst']

In [17]:
#Now Letus do the encoding for the 'object columns' i.e,. diagnosis

diagnosis_codes = {'B': 0, 'M': 1}

raw_data['diagnosis_codes'] = raw_data.diagnosis.map(diagnosis_codes)

In [18]:
cancer_no = raw_data[raw_data['diagnosis_codes'] == 0]

In [19]:
raw_data

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,diagnosis_codes
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890,1
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902,1
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758,1
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300,1
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,...,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,1
565,926682,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,...,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,1
566,926954,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,...,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,1
567,927241,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,...,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,1
568,92751,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,...,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039,0

In [20]:
#Now lets use the scalling for numeric columns

In [21]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

raw_data[numeric_columns] = scaler.fit_transform(raw_data[numeric_columns])

In [22]:
raw_data

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,diagnosis_codes
0,842302,M,0.521037,0.022658,0.545989,0.363733,0.593753,0.792037,0.703140,0.731113,...,0.141525,0.668310,0.450698,0.601136,0.619292,0.568610,0.912027,0.598462,0.418864,1
1,842517,M,0.643144,0.272574,0.615783,0.501591,0.289880,0.181768,0.203608,0.348757,...,0.303571,0.539818,0.435214,0.347553,0.154563,0.192971,0.639175,0.233590,0.222878,1
2,84300903,M,0.601496,0.390260,0.595743,0.449417,0.514309,0.431017,0.462512,0.635686,...,0.360075,0.508442,0.374508,0.483590,0.385375,0.359744,0.835052,0.403706,0.213433,1
3,84348301,M,0.210090,0.360839,0.233501,0.102906,0.811321,0.811361,0.565604,0.522863,...,0.385928,0.241347,0.094008,0.915472,0.814012,0.548642,0.884880,1.000000,0.773711,1
4,84358402,M,0.629893,0.156578,0.630986,0.489290,0.430351,0.347893,0.463918,0.518390,...,0.123934,0.506948,0.341575,0.437364,0.172415,0.319489,0.558419,0.157500,0.142595,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,M,0.690000,0.428813,0.678668,0.566490,0.526948,0.296055,0.571462,0.690358,...,0.383262,0.576174,0.452664,0.461137,0.178527,0.328035,0.761512,0.097575,0.105667,1
565,926682,M,0.622320,0.626987,0.604036,0.474019,0.407782,0.257714,0.337395,0.486630,...,0.699094,0.520892,0.379915,0.300007,0.159997,0.256789,0.559450,0.198502,0.074315,1
566,926954,M,0.455251,0.621238,0.445788,0.303118,0.288165,0.254340,0.216753,0.263519,...,0.589019,0.379949,0.230731,0.282177,0.273705,0.271805,0.487285,0.128721,0.151909,1
567,927241,M,0.644564,0.663510,0.665538,0.475716,0.588336,0.790197,0.823336,0.755467,...,0.730277,0.668310,0.402035,0.619626,0.815758,0.749760,0.910653,0.497142,0.452315,1
568,92751,B,0.036869,0.501522,0.028540,0.015907,0.000000,0.074351,0.000000,0.000000,...,0.489072,0.043578,0.020497,0.124084,0.036043,0.000000,0.000000,0.257441,0.100682,0

In [23]:
raw_data.describe()

,id,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,diagnosis_codes
count,5.690000e+02,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,...,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000
mean,3.037183e+07,0.338222,0.323965,0.332935,0.216920,0.394785,0.260601,0.208058,0.243137,0.379605,...,0.363998,0.283138,0.170906,0.404138,0.220212,0.217403,0.393836,0.263307,0.189596,0.372583
std,1.250206e+08,0.166787,0.145453,0.167915,0.149274,0.126967,0.161992,0.186785,0.192857,0.138456,...,0.163813,0.167352,0.139932,0.150779,0.152649,0.166633,0.225884,0.121954,0.118466,0.483918
min,8.670000e+03,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,8.692180e+05,0.223342,0.218465,0.216847,0.117413,0.304595,0.139685,0.069260,0.100944,0.282323,...,0.241471,0.167837,0.081130,0.300007,0.116337,0.091454,0.223127,0.185098,0.107700,0.000000
50%,9.060240e+05,0.302381,0.308759,0.293345,0.172895,0.390358,0.224679,0.144189,0.166501,0.369697,...,0.356876,0.235320,0.123206,0.397081,0.179110,0.181070,0.343402,0.247782,0.163977,0.000000
75%,8.813129e+06,0.416442,0.408860,0.416765,0.271135,0.475490,0.340531,0.306232,0.367793,0.453030,...,0.471748,0.373475,0.220901,0.494156,0.302520,0.305831,0.554639,0.318155,0.242949,1.000000
max,9.113205e+08,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [24]:
#Now first lets use Logestic regression model and after that we will use Decision Trees and Random Forest.

#we will split the train_data, test_data, validation_data

In [25]:
main_data = raw_data[numeric_columns]

In [26]:
main_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 30 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   radius_mean              569 non-null    float64
 1   texture_mean             569 non-null    float64
 2   perimeter_mean           569 non-null    float64
 3   area_mean                569 non-null    float64
 4   smoothness_mean          569 non-null    float64
 5   compactness_mean         569 non-null    float64
 6   concavity_mean           569 non-null    float64
 7   concave points_mean      569 non-null    float64
 8   symmetry_mean            569 non-null    float64
 9   fractal_dimension_mean   569 non-null    float64
 10  radius_se                569 non-null    float64
 11  texture_se               569 non-null    float64
 12  perimeter_se             569 non-null    float64
 13  area_se                  569 non-null    float64
 14  smoothness_se            569 non-null    float64
 15  compactness_se           569 non-null    float64
 16  concavity_se             569 non-null    float64
 17  concave points_se        569 non-null    float64
 18  symmetry_se              569 non-null    float64
 19  fractal_dimension_se     569 non-null    float64
 20  radius_worst             569 non-null    float64
 21  texture_worst            569 non-null    float64
 22  perimeter_worst          569 non-null    float64
 23  area_worst               569 non-null    float64
 24  smoothness_worst         569 non-null    float64
 25  compactness_worst        569 non-null    float64
 26  concavity_worst          569 non-null    float64
 27  concave points_worst     569 non-null    float64
 28  symmetry_worst           569 non-null    float64
 29  fractal_dimension_worst  569 non-null    float64
dtypes: float64(30)
memory usage: 133.5 KB

In [27]:
target_data = raw_data['diagnosis_codes']

In [28]:
from sklearn.model_selection import train_test_split

train_val_data, test_data, train_val_target, test_target = train_test_split(raw_data, target_data, test_size = 0.2, random_state = 42)

train_data, val_data, train_target, val_target = train_test_split(train_val_data,train_val_target, test_size = 0.2, random_state = 42)

In [29]:
print(train_data.shape)
print(val_data.shape)
print(test_data.shape)
print(train_target.shape)

(364, 33)
(91, 33)
(114, 33)
(364,)

In [30]:
numeric_columns

['radius_mean',
 'texture_mean',
 'perimeter_mean',
 'area_mean',
 'smoothness_mean',
 'compactness_mean',
 'concavity_mean',
 'concave points_mean',
 'symmetry_mean',
 'fractal_dimension_mean',
 'radius_se',
 'texture_se',
 'perimeter_se',
 'area_se',
 'smoothness_se',
 'compactness_se',
 'concavity_se',
 'concave points_se',
 'symmetry_se',
 'fractal_dimension_se',
 'radius_worst',
 'texture_worst',
 'perimeter_worst',
 'area_worst',
 'smoothness_worst',
 'compactness_worst',
 'concavity_worst',
 'concave points_worst',
 'symmetry_worst',
 'fractal_dimension_worst']

In [31]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(train_data[numeric_columns], train_target)

LogisticRegression()

In [32]:
train_prediction = model.predict(train_data[numeric_columns])

In [33]:
train_prediction

array([0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0])

In [34]:
#Now Lets calculate the train probability for train_data, val_data

In [35]:
model.classes_

array([0, 1])

In [36]:
import numpy as np

prediction_prob = model.predict_proba(train_data[numeric_columns])

np.set_printoptions(suppress = True)

print(prediction_prob)

[[0.63423021 0.36576979]
 [0.00428017 0.99571983]
 [0.78633558 0.21366442]
 [0.92386138 0.07613862]
 [0.94151581 0.05848419]
 [0.9436627  0.0563373 ]
 [0.01026252 0.98973748]
 [0.0414525  0.9585475 ]
 [0.91097955 0.08902045]
 [0.96637942 0.03362058]
 [0.87696453 0.12303547]
 [0.8408842  0.1591158 ]
 [0.04040187 0.95959813]
 [0.00261976 0.99738024]
 [0.06831239 0.93168761]
 [0.75094377 0.24905623]
 [0.90680626 0.09319374]
 [0.97944882 0.02055118]
 [0.00029539 0.99970461]
 [0.03289994 0.96710006]
 [0.99248224 0.00751776]
 [0.6514736  0.3485264 ]
 [0.99542146 0.00457854]
 [0.98622969 0.01377031]
 [0.13169822 0.86830178]
 [0.00221271 0.99778729]
 [0.95638308 0.04361692]
 [0.96873369 0.03126631]
 [0.98995121 0.01004879]
 [0.91120685 0.08879315]
 [0.91451519 0.08548481]
 [0.50168471 0.49831529]
 [0.94860683 0.05139317]
 [0.95315665 0.04684335]
 [0.13893376 0.86106624]
 [0.90726577 0.09273423]
 [0.73702706 0.26297294]
 [0.93802844 0.06197156]
 [0.09305897 0.90694103]
 [0.97405048 0.02594952]
 [0.98886753 0.01113247]
 [0.95648632 0.04351368]
 [0.00792688 0.99207312]
 [0.95984001 0.04015999]
 [0.97010276 0.02989724]
 [0.99017869 0.00982131]
 [0.00696312 0.99303688]
 [0.82141094 0.17858906]
 [0.97252271 0.02747729]
 [0.95842648 0.04157352]
 [0.99682333 0.00317667]
 [0.44082621 0.55917379]
 [0.97909292 0.02090708]
 [0.0033536  0.9966464 ]
 [0.88449086 0.11550914]
 [0.93907876 0.06092124]
 [0.97078121 0.02921879]
 [0.97174534 0.02825466]
 [0.93141949 0.06858051]
 [0.92637105 0.07362895]
 [0.03281031 0.96718969]
 [0.9840006  0.0159994 ]
 [0.60826134 0.39173866]
 [0.9916336  0.0083664 ]
 [0.3829238  0.6170762 ]
 [0.02332427 0.97667573]
 [0.89258441 0.10741559]
 [0.03270655 0.96729345]
 [0.00016832 0.99983168]
 [0.99837185 0.00162815]
 [0.98133925 0.01866075]
 [0.06955647 0.93044353]
 [0.99055833 0.00944167]
 [0.05252783 0.94747217]
 [0.89311937 0.10688063]
 [0.01445304 0.98554696]
 [0.18329562 0.81670438]
 [0.17296419 0.82703581]
 [0.21828326 0.78171674]
 [0.84449243 0.15550757]
 [0.95695755 0.04304245]
 [0.01749481 0.98250519]
 [0.97622042 0.02377958]
 [0.97615335 0.02384665]
 [0.95275333 0.04724667]
 [0.72120697 0.27879303]
 [0.89117554 0.10882446]
 [0.23402182 0.76597818]
 [0.01339635 0.98660365]
 [0.55187692 0.44812308]
 [0.43087132 0.56912868]
 [0.98895223 0.01104777]
 [0.43520729 0.56479271]
 [0.99779351 0.00220649]
 [0.96252101 0.03747899]
 [0.94290934 0.05709066]
 [0.67746088 0.32253912]
 [0.97038897 0.02961103]
 [0.35819964 0.64180036]
 [0.0285063  0.9714937 ]
 [0.83582286 0.16417714]
 [0.75761298 0.24238702]
 [0.03428158 0.96571842]
 [0.90265778 0.09734222]
 [0.0702757  0.9297243 ]
 [0.51070065 0.48929935]
 [0.97614966 0.02385034]
 [0.79901883 0.20098117]
 [0.03955338 0.96044662]
 [0.99374818 0.00625182]
 [0.32002511 0.67997489]
 [0.99560286 0.00439714]
 [0.87562226 0.12437774]
 [0.9864545  0.0135455 ]
 [0.96751602 0.03248398]
 [0.00776574 0.99223426]
 [0.91920734 0.08079266]
 [0.85807649 0.14192351]
 [0.18266202 0.81733798]
 [0.77905092 0.22094908]
 [0.90156484 0.09843516]
 [0.93966261 0.06033739]
 [0.99064208 0.00935792]
 [0.7776092  0.2223908 ]
 [0.9887135  0.0112865 ]
 [0.15972145 0.84027855]
 [0.99263075 0.00736925]
 [0.98048317 0.01951683]
 [0.08134558 0.91865442]
 [0.35533535 0.64466465]
 [0.00000197 0.99999803]
 [0.97986343 0.02013657]
 [0.01388995 0.98611005]
 [0.97910039 0.02089961]
 [0.04597836 0.95402164]
 [0.98657044 0.01342956]
 [0.05790058 0.94209942]
 [0.19820505 0.80179495]
 [0.99201126 0.00798874]
 [0.00557938 0.99442062]
 [0.98081953 0.01918047]
 [0.95314492 0.04685508]
 [0.98652967 0.01347033]
 [0.82078609 0.17921391]
 [0.00003193 0.99996807]
 [0.27449326 0.72550674]
 [0.36497971 0.63502029]
 [0.97517572 0.02482428]
 [0.90488542 0.09511458]
 [0.93269336 0.06730664]
 [0.00335044 0.99664956]
 [0.00019901 0.99980099]
 [0.00042838 0.99957162]
 [0.9910247  0.0089753 ]
 [0.06940859 0.93059141]
 [0.00309817 0.99690183]
 [0.0039711  0.9960289 ]
 [0.9756909  0.0243091 ]
 [0.9810918  0.0189082 ]
 [0.58806849 0.41193151]
 [0.68264106 0.31735894]
 [0.97569282 0.02430718]
 [0.94769437 0.05230563]
 [0.19997085 0.80002915]
 [0.98706801 0.01293199]
 [0.95213658 0.04786342]
 [0.98324566 0.01675434]
 [0.42795194 0.57204806]
 [0.96927091 0.03072909]
 [0.21185948 0.78814052]
 [0.1180224  0.8819776 ]
 [0.03186469 0.96813531]
 [0.92383463 0.07616537]
 [0.69075686 0.30924314]
 [0.00199928 0.99800072]
 [0.02076911 0.97923089]
 [0.93872254 0.06127746]
 [0.27307442 0.72692558]
 [0.74837026 0.25162974]
 [0.0069584  0.9930416 ]
 [0.211016   0.788984  ]
 [0.10495216 0.89504784]
 [0.70883522 0.29116478]
 [0.97657037 0.02342963]
 [0.64885643 0.35114357]
 [0.89467026 0.10532974]
 [0.00254121 0.99745879]
 [0.95447344 0.04552656]
 [0.91509236 0.08490764]
 [0.36649104 0.63350896]
 [0.03819532 0.96180468]
 [0.85415016 0.14584984]
 [0.00473597 0.99526403]
 [0.95372803 0.04627197]
 [0.14226124 0.85773876]
 [0.9739665  0.0260335 ]
 [0.7569847  0.2430153 ]
 [0.90638902 0.09361098]
 [0.9936829  0.0063171 ]
 [0.95216747 0.04783253]
 [0.90547837 0.09452163]
 [0.90497887 0.09502113]
 [0.65364765 0.34635235]
 [0.86205873 0.13794127]
 [0.40820037 0.59179963]
 [0.98604052 0.01395948]
 [0.91474822 0.08525178]
 [0.00626112 0.99373888]
 [0.01638156 0.98361844]
 [0.07648272 0.92351728]
 [0.98038454 0.01961546]
 [0.99019274 0.00980726]
 [0.94773115 0.05226885]
 [0.91355809 0.08644191]
 [0.79939603 0.20060397]
 [0.98990081 0.01009919]
 [0.00063109 0.99936891]
 [0.41211515 0.58788485]
 [0.95935248 0.04064752]
 [0.7635175  0.2364825 ]
 [0.846739   0.153261  ]
 [0.89999929 0.10000071]
 [0.9934695  0.0065305 ]
 [0.00003798 0.99996202]
 [0.60251151 0.39748849]
 [0.0000342  0.9999658 ]
 [0.82709777 0.17290223]
 [0.99137561 0.00862439]
 [0.71768611 0.28231389]
 [0.99032982 0.00967018]
 [0.98186721 0.01813279]
 [0.47089438 0.52910562]
 [0.23286214 0.76713786]
 [0.00497681 0.99502319]
 [0.11606393 0.88393607]
 [0.99210759 0.00789241]
 [0.70123148 0.29876852]
 [0.95986221 0.04013779]
 [0.02179261 0.97820739]
 [0.02790603 0.97209397]
 [0.8695825  0.1304175 ]
 [0.96761069 0.03238931]
 [0.01341704 0.98658296]
 [0.98090611 0.01909389]
 [0.37145439 0.62854561]
 [0.02394417 0.97605583]
 [0.92981394 0.07018606]
 [0.00348421 0.99651579]
 [0.08986887 0.91013113]
 [0.937136   0.062864  ]
 [0.96628338 0.03371662]
 [0.75428571 0.24571429]
 [0.24157417 0.75842583]
 [0.91170086 0.08829914]
 [0.93622137 0.06377863]
 [0.49423816 0.50576184]
 [0.97437023 0.02562977]
 [0.09551055 0.90448945]
 [0.99244721 0.00755279]
 [0.93564547 0.06435453]
 [0.8164162  0.1835838 ]
 [0.89821139 0.10178861]
 [0.96256875 0.03743125]
 [0.87752464 0.12247536]
 [0.95160484 0.04839516]
 [0.73337283 0.26662717]
 [0.96695639 0.03304361]
 [0.00081242 0.99918758]
 [0.89465841 0.10534159]
 [0.93995425 0.06004575]
 [0.77237148 0.22762852]
 [0.70160618 0.29839382]
 [0.02324127 0.97675873]
 [0.63681942 0.36318058]
 [0.84547195 0.15452805]
 [0.00778931 0.99221069]
 [0.96246394 0.03753606]
 [0.98953389 0.01046611]
 [0.95952364 0.04047636]
 [0.91277544 0.08722456]
 [0.99481192 0.00518808]
 [0.95489051 0.04510949]
 [0.99530841 0.00469159]
 [0.91511869 0.08488131]
 [0.9185691  0.0814309 ]
 [0.95328771 0.04671229]
 [0.99523015 0.00476985]
 [0.01222621 0.98777379]
 [0.98806475 0.01193525]
 [0.11746681 0.88253319]
 [0.08875397 0.91124603]
 [0.99084659 0.00915341]
 [0.68070069 0.31929931]
 [0.00025461 0.99974539]
 [0.98996477 0.01003523]
 [0.92505893 0.07494107]
 [0.96895076 0.03104924]
 [0.87439165 0.12560835]
 [0.49976644 0.50023356]
 [0.00481513 0.99518487]
 [0.95200865 0.04799135]
 [0.0125763  0.9874237 ]
 [0.98993614 0.01006386]
 [0.9921175  0.0078825 ]
 [0.96825598 0.03174402]
 [0.00701789 0.99298211]
 [0.92623303 0.07376697]
 [0.92021481 0.07978519]
 [0.97654707 0.02345293]
 [0.01444211 0.98555789]
 [0.00170365 0.99829635]
 [0.90413909 0.09586091]
 [0.16141043 0.83858957]
 [0.96057025 0.03942975]
 [0.98356326 0.01643674]
 [0.71651119 0.28348881]
 [0.70519421 0.29480579]
 [0.03479887 0.96520113]
 [0.81093376 0.18906624]
 [0.90186025 0.09813975]
 [0.97855987 0.02144013]
 [0.96360742 0.03639258]
 [0.07319029 0.92680971]
 [0.54291429 0.45708571]
 [0.96156635 0.03843365]
 [0.10524548 0.89475452]
 [0.81188189 0.18811811]
 [0.99533502 0.00466498]
 [0.93880756 0.06119244]
 [0.93705311 0.06294689]
 [0.99117019 0.00882981]
 [0.02940104 0.97059896]
 [0.0077091  0.9922909 ]
 [0.99663528 0.00336472]
 [0.07139689 0.92860311]
 [0.98403948 0.01596052]
 [0.59293218 0.40706782]
 [0.98487973 0.01512027]
 [0.14181514 0.85818486]
 [0.98690744 0.01309256]
 [0.04899718 0.95100282]
 [0.50423187 0.49576813]
 [0.96348219 0.03651781]
 [0.87651561 0.12348439]
 [0.98132495 0.01867505]
 [0.68589223 0.31410777]
 [0.31029777 0.68970223]
 [0.81510211 0.18489789]
 [0.96179742 0.03820258]
 [0.99536382 0.00463618]
 [0.98736056 0.01263944]
 [0.97163937 0.02836063]
 [0.97083711 0.02916289]
 [0.97082992 0.02917008]
 [0.11620117 0.88379883]
 [0.93817811 0.06182189]
 [0.87349528 0.12650472]
 [0.85909097 0.14090903]
 [0.34179131 0.65820869]
 [0.15543836 0.84456164]
 [0.10016741 0.89983259]
 [0.97447846 0.02552154]
 [0.53917961 0.46082039]
 [0.95922957 0.04077043]]

In [37]:
#Now we need to check the accuracy of the predicted and actual data for training data

In [38]:
from sklearn.metrics import accuracy_score

train_data_accuracy = accuracy_score(train_target, train_prediction, normalize=True)

print("Accuracy: ", train_data_accuracy*100)

Accuracy:  97.25274725274726

In [39]:
#So, our training data accuracy is 97.25%
#Now we will check the confusion matrix for this training data.

In [40]:
############################## IMPORTANT ###################################################################
#We Need to use CONFUSION MATRIX to identify, where our model is actually getting failed.
#This CONFUSION MATRIX defines, where our model is actually getting failed.
#It gives us 1.TRUE NEGATIVE(TN), 2. TRUE POSITIVE(TP), 3. FALSE NEGATIVE(FN), 4. FALSE POSITIVE(FP)
# With This Confusion matrix we can extract 1.ACCURACY 2. PRECISION 3. RECALL 4.F1-SCORE
#1.ACCURACY = (TN + TP)/(TN + TP+ FN+ FP) #
#2. PRECISION = TP/(TP + FP) # Of everything the model predicted positive, how many were actually positive?
#3. RECALL = TP/(TP + FN) # Of everything that was actually positive, how many did the model find?
#4. F1-SCORE = F1 = 2 × (Precision × Recall) / (Precision + Recall) # Combines precision and recall:

In [41]:
#NOW lets calculate the CONFUSION MATRIX for the training data.

In [42]:
from sklearn.metrics import confusion_matrix

confusion_mat = confusion_matrix(train_target, train_prediction)

print(confusion_mat)

[[231   0]
 [ 10 123]]

In [43]:
############################################### IMPORTANT ###################################################
# Now we can find TP, FP, TN, FN from this confusion matrix and we can find accuracy, precision, recall, f1-score

In [44]:
TN, FP, FN, TP = confusion_matrix(train_target, train_prediction).ravel()

print("True Negative:", TN)
print("False Positive:", FP)
print("False Negative:", FN)
print("True Positive:", TP)

True Negative: 231
False Positive: 0
False Negative: 10
True Positive: 123

In [45]:
#######################IMPORTANT###################################
#nOW LET US TEST OUR MODEL ON VAL_DATA

In [46]:
validation_prediction = model.predict(val_data[numeric_columns])

validation_prediction

array([1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0])

In [47]:
val_target

95     1
93     0
401    0
345    0
194    1
      ..
71     0
16     1
346    0
149    0
312    0
Name: diagnosis_codes, Length: 91, dtype: int64

In [48]:
#Now lets calculate accuracy using function

from sklearn.metrics import accuracy_score

val_data_accuracy = accuracy_score(val_target, validation_prediction)

print("validation_Accuracy: ", val_data_accuracy * 100)

validation_Accuracy:  94.5054945054945

In [49]:
#Lets create the confusion matrix and check the accuracy rate.

In [50]:
from sklearn.metrics import confusion_matrix

val_confusion_matrix = confusion_matrix(val_target, validation_prediction)

print(val_confusion_matrix)

[[53  2]
 [ 3 33]]

In [51]:
TN, FP, FN, TP = confusion_matrix(val_target, validation_prediction).ravel()

print("True Negative:", TN)
print("False Positive:", FP)
print("False Negative:", FN)
print("True Positive:", TP)

True Negative: 53
False Positive: 2
False Negative: 3
True Positive: 33

In [52]:
#I think the accuracy is good in between training data and validation data.
#Now we will test our model on the test_data

In [53]:
Test_prediction = model.predict(test_data[numeric_columns])

Test_prediction

array([0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1])

In [54]:
test_target

204    0
70     1
131    1
431    0
540    0
      ..
486    0
75     1
249    0
238    0
265    1
Name: diagnosis_codes, Length: 114, dtype: int64

In [55]:
# Now, we will find the accuracy score and confusion matrix

In [56]:
test_prediction_accuracy = accuracy_score(test_target, Test_prediction)

print("Test_prediction_accuracy: ", test_prediction_accuracy*100)

Test_prediction_accuracy:  97.36842105263158

In [57]:
#We will find confusion matrix

Test_confusion_matrix = confusion_matrix(test_target, Test_prediction)

print(Test_confusion_matrix)

[[70  1]
 [ 2 41]]

In [58]:
TN, FP, FN, TP = confusion_matrix(test_target, Test_prediction).ravel()

print("True Negative:", TN)
print("False Positive:", FP)
print("False Negative:", FN)
print("True Positive:", TP)

True Negative: 70
False Positive: 1
False Negative: 2
True Positive: 41

In [59]:
########################################## CLOSE OF LOGESTIC REGRESSION ##################################
#OUR ACCURACY SCORES IS VERY GOOD. OUR MODEL IS PERFORMING EXTRODINARILY

In [60]:
#lETS TEST BY GIVING ONE SINGLE ROW
import pandas as pd

def predict_random_data(single_row):
  input_data = pd.DataFrame([single_row])
  input_data[numeric_columns] = scaler.transform(input_data[numeric_columns])
  X_input = input_data[numeric_columns]

  new_prediction = model.predict(X_input)[0]
  new_pred_prob = model.predict_proba(X_input)[0][list(model.classes_).index(new_prediction)]


  return new_prediction, new_pred_prob

In [61]:
#JUST FINDING THE DATA TO INSERT IN A SINGLE ROW(Just Learn)
import pandas as pd

daw_data = pd.read_csv(data)

daw_data

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,...,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,NaN
565,926682,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,...,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,NaN
566,926954,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,...,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,NaN
567,927241,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,...,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,NaN
568,92751,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,...,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039,NaN

In [62]:
import pandas as pd

single_row = {
               'diagnosis':'M',
               'radius_mean' :17.99,
               'texture_mean': 10.38,
               'perimeter_mean':122.8 ,
               'area_mean': 1001.0 ,
               'smoothness_mean':0.1184,
               'compactness_mean': 0.2776,
               'concavity_mean': 0.3001,
               'concave points_mean': 0.1471,
               'symmetry_mean':0.2419,
               'fractal_dimension_mean':0.07871,
               'radius_se':1.095,
               'texture_se':0.9053,
               'perimeter_se':8.589,
               'area_se':153.4,
               'smoothness_se':0.006399,
               'compactness_se':0.04904,
               'concavity_se':0.05373,
               'concave points_se' : 0.01587,
               'symmetry_se': 0.03003,
               'fractal_dimension_se': 0.006193,
               'radius_worst': 25.380,
               'texture_worst':17.33,
               'perimeter_worst':184.60,
               'area_worst': 2019.0,
               'smoothness_worst':0.16220,
               'compactness_worst':0.66560,
               'concavity_worst': 0.7119,
               'concave points_worst': 0.2654,
               'symmetry_worst':0.4601,
               'fractal_dimension_worst':0.19890
}

predict_random_data(single_row)

(np.int64(1), np.float64(0.9981236930506258))

In [63]:
import pandas as pd

single_row = {
    'diagnosis': 'B',
    'radius_mean': 13.54,
    'texture_mean': 14.36,
    'perimeter_mean': 87.46,
    'area_mean': 566.3,
    'smoothness_mean': 0.09779,
    'compactness_mean': 0.08129,
    'concavity_mean': 0.06664,
    'concave points_mean': 0.04781,
    'symmetry_mean': 0.1885,
    'fractal_dimension_mean': 0.05766,
    'radius_se': 0.2699,
    'texture_se': 0.7886,
    'perimeter_se': 2.058,
    'area_se': 23.56,
    'smoothness_se': 0.008462,
    'compactness_se': 0.0146,
    'concavity_se': 0.02387,
    'concave points_se': 0.01315,
    'symmetry_se': 0.0198,
    'fractal_dimension_se': 0.0023,
    'radius_worst': 15.11,
    'texture_worst': 19.26,
    'perimeter_worst': 99.7,
    'area_worst': 711.2,
    'smoothness_worst': 0.144,
    'compactness_worst': 0.1773,
    'concavity_worst': 0.239,
    'concave points_worst': 0.1288,
    'symmetry_worst': 0.2977,
    'fractal_dimension_worst': 0.07259
}

predict_random_data(single_row)

(np.int64(0), np.float64(0.8329711084639182))

In [64]:
import pandas as pd

single_row = {
    'diagnosis': 'M',
    'radius_mean': 18.25,
    'texture_mean': 19.98,
    'perimeter_mean': 119.6,
    'area_mean': 1040.0,
    'smoothness_mean': 0.09463,
    'compactness_mean': 0.109,
    'concavity_mean': 0.1127,
    'concave points_mean': 0.074,
    'symmetry_mean': 0.1794,
    'fractal_dimension_mean': 0.05742,
    'radius_se': 0.4467,
    'texture_se': 0.7732,
    'perimeter_se': 3.18,
    'area_se': 53.91,
    'smoothness_se': 0.004314,
    'compactness_se': 0.01382,
    'concavity_se': 0.02254,
    'concave points_se': 0.01039,
    'symmetry_se': 0.01369,
    'fractal_dimension_se': 0.002179,
    'radius_worst': 22.88,
    'texture_worst': 27.66,
    'perimeter_worst': 153.2,
    'area_worst': 1606.0,
    'smoothness_worst': 0.1442,
    'compactness_worst': 0.2576,
    'concavity_worst': 0.3784,
    'concave points_worst': 0.1932,
    'symmetry_worst': 0.3063,
    'fractal_dimension_worst': 0.08368
}

predict_random_data(single_row)

(np.int64(1), np.float64(0.948924597428639))

In [65]:
import pandas as pd

single_row = {
    'diagnosis': 'B',
    'radius_mean': 11.52, 'texture_mean': 18.45, 'perimeter_mean': 73.80, 'area_mean': 407.5,
    'smoothness_mean': 0.09345, 'compactness_mean': 0.05924, 'concavity_mean': 0.02741, 'concave points_mean': 0.02058,
    'symmetry_mean': 0.1619, 'fractal_dimension_mean': 0.06201, 'radius_se': 0.2543, 'texture_se': 0.9542,
    'perimeter_se': 1.832, 'area_se': 18.24, 'smoothness_se': 0.006241, 'compactness_se': 0.01152,
    'concavity_se': 0.01524, 'concave points_se': 0.008432, 'symmetry_se': 0.01892, 'fractal_dimension_se': 0.002143,
    'radius_worst': 12.84, 'texture_worst': 24.15, 'perimeter_worst': 83.42, 'area_worst': 503.4,
    'smoothness_worst': 0.1243, 'compactness_worst': 0.1154, 'concavity_worst': 0.0924, 'concave points_worst': 0.05632,
    'symmetry_worst': 0.2435, 'fractal_dimension_worst': 0.07123

}

predict_random_data(single_row)

(np.int64(0), np.float64(0.9731300243465366))

In [66]:
import pandas as pd

single_row = {
    'diagnosis': 'M',
    'radius_mean': 20.15, 'texture_mean': 22.34, 'perimeter_mean': 133.20, 'area_mean': 1264.0,
    'smoothness_mean': 0.10842, 'compactness_mean': 0.16450, 'concavity_mean': 0.21450, 'concave points_mean': 0.12450,
    'symmetry_mean': 0.1984, 'fractal_dimension_mean': 0.06124, 'radius_se': 0.6342, 'texture_se': 1.1523,
    'perimeter_se': 4.562, 'area_se': 78.43, 'smoothness_se': 0.005842, 'compactness_se': 0.03542,
    'concavity_se': 0.04852, 'concave points_se': 0.01845, 'symmetry_se': 0.02241, 'fractal_dimension_se': 0.003945,
    'radius_worst': 25.42, 'texture_worst': 30.12, 'perimeter_worst': 172.40, 'area_worst': 1984.0,
    'smoothness_worst': 0.1523, 'compactness_worst': 0.4124, 'concavity_worst': 0.5432, 'concave points_worst': 0.2241,
    'symmetry_worst': 0.3421, 'fractal_dimension_worst': 0.09842

}

predict_random_data(single_row)

(np.int64(1), np.float64(0.9971598890587472))

In [ ]:
#Now let us do this in DECISION TREE AND RANDOM FOREST.

In [67]:
raw_data

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,diagnosis_codes
0,842302,M,0.521037,0.022658,0.545989,0.363733,0.593753,0.792037,0.703140,0.731113,...,0.141525,0.668310,0.450698,0.601136,0.619292,0.568610,0.912027,0.598462,0.418864,1
1,842517,M,0.643144,0.272574,0.615783,0.501591,0.289880,0.181768,0.203608,0.348757,...,0.303571,0.539818,0.435214,0.347553,0.154563,0.192971,0.639175,0.233590,0.222878,1
2,84300903,M,0.601496,0.390260,0.595743,0.449417,0.514309,0.431017,0.462512,0.635686,...,0.360075,0.508442,0.374508,0.483590,0.385375,0.359744,0.835052,0.403706,0.213433,1
3,84348301,M,0.210090,0.360839,0.233501,0.102906,0.811321,0.811361,0.565604,0.522863,...,0.385928,0.241347,0.094008,0.915472,0.814012,0.548642,0.884880,1.000000,0.773711,1
4,84358402,M,0.629893,0.156578,0.630986,0.489290,0.430351,0.347893,0.463918,0.518390,...,0.123934,0.506948,0.341575,0.437364,0.172415,0.319489,0.558419,0.157500,0.142595,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,M,0.690000,0.428813,0.678668,0.566490,0.526948,0.296055,0.571462,0.690358,...,0.383262,0.576174,0.452664,0.461137,0.178527,0.328035,0.761512,0.097575,0.105667,1
565,926682,M,0.622320,0.626987,0.604036,0.474019,0.407782,0.257714,0.337395,0.486630,...,0.699094,0.520892,0.379915,0.300007,0.159997,0.256789,0.559450,0.198502,0.074315,1
566,926954,M,0.455251,0.621238,0.445788,0.303118,0.288165,0.254340,0.216753,0.263519,...,0.589019,0.379949,0.230731,0.282177,0.273705,0.271805,0.487285,0.128721,0.151909,1
567,927241,M,0.644564,0.663510,0.665538,0.475716,0.588336,0.790197,0.823336,0.755467,...,0.730277,0.668310,0.402035,0.619626,0.815758,0.749760,0.910653,0.497142,0.452315,1
568,92751,B,0.036869,0.501522,0.028540,0.015907,0.000000,0.074351,0.000000,0.000000,...,0.489072,0.043578,0.020497,0.124084,0.036043,0.000000,0.000000,0.257441,0.100682,0